# MikroTik RouterOS Script
# Generated by Compiler Project

# Initialization
{
    # Section: device (Type: device)
    /system identity
    vendor=""mikrotik""
    ==""test""
    # Section: interfaces (Type: interfaces)
    /interface
    # Section: : (Type: custom)
    /:
    type=""ethernet""
    description=""Test interface""
    # Section: ip (Type: custom)
    /ip
    address="192.168.1.1/24"
}
